title: Anveshak
lang: en-US
description: Some of my fun projects and some docs from Anveshak
favicon: favicon.ico

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

edit: false

copyright:
  revision: false


# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
