title: pa1Tech | Anveshak
lang: en-US
description: Some of my fun projects and docs from Anveshak

edit: false

copyright: 
  since: false
  revision: false

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
